# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Reddit-RxSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reddit-RxSwiftDemo

	pod 'RxSwift', '6.2.0'
	pod 'RxCocoa', '6.2.0'
	pod 'RxDataSources', '~> 5.0'
	pod "RxGesture"
	pod 'SnapKit'
	pod 'Kingfisher'
	pod 'Alamofire'


  target 'Reddit-RxSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Reddit-RxSwiftDemoUITests' do
    # Pods for testing
  end

end
